SalesForceProj/src/objects/DynamicPickList__c.object
<CustomObject>
    <fields>
        <fullName>PickListValue__c</fullName>
        <label>PickListValue</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>DynamicPickList</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DynamicPickLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesForceProj/src/classes/dynamicpicklist.cls
public class dynamicpicklist {

    public String city{get; set;}
    public String newpicklistvalue{get; set;}
    
    public List<SelectOption> getCityNames() {
    
        List<SelectOption> options= new List<SelectOption>();
        List<DynamicPickList__c> cityList = new List<DynamicPickList__c>();
        cityList = [select Id,PickListValue__c from DynamicPickList__c];
        options.add(new SelectOption('--None--','--None--'));
        
        for (Integer j=0;j<cityList.size();j++) {
            
            options.add(new SelectOption(cityList[j].PickListValue__c,cityList[j].PickListValue__c));
        
        }       
        
        return options;
    
    }
    
    public void saverec() {
    
     DynamicPickList__c newrec= new DynamicPickList__c(PickListValue__c=newpicklistvalue);
     insert newrec;
     newpicklistvalue=NULL;
    
    }

}